#!/bin/bash
gcc -o keygen keygen.c
gcc -o otp_enc_d otp_enc_d.c
gcc -o otp_enc otp_enc.c
gcc -o otp_dec_d otp_dec_d.c
gcc -o otp_dec otp_dec.c

chmod +x keygen otp_enc_d otp_enc otp_dec_d otp_dec p4gradingscript
echo "compile success"
